version: '3'
services:
  loadbalancer:
    image: nginx
    ports: 
      - "443:443"
    volumes:
      - "$HOME/nginx:/etc/nginx:ro"
    depends_on:
      - closetdojo_beta
      - closetoctant_beta
    restart: always
  closetdojo:
    image: devsecopscloset/closet_dojo:dev
    networks:
      closet:
        ipv4_address: 192.168.0.2
    restart: always
    deploy:
      mode: replicated
      replicas: 1
  closetoctant:
    image: devsecopscloset/octant:dev
    volumes:
      - "$HOME/kubeconfig:/kubeconfig:ro"
    networks:
      closet:
        ipv4_address: 192.168.0.3
    restart: always
    deploy:
      mode: replicated
      replicas: 1

networks:
  closet:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/24
