version: '3'
services:
  loadbalancer:
    image: nginx
    ports: 
      - "443:443"
    volumes:
      - "$HOME/nginx:/etc/nginx:ro"
    depends_on:
      - closetdojo_beta
      - closetoctant_beta
    restart: always
  closetdojo_alpha:
    image: devsecopscloset/closet_dojo:dev
    networks:
      closet:
        ipv4_address: 192.168.0.2
    restart: always
  closetdojo_beta:
    image: devsecopscloset/closet_dojo:dev
    networks:
      closet:
        ipv4_address: 192.168.0.3
    depends_on:
      - closetdojo_alpha
    restart: always
  closetoctant_alpha:
    image: devsecopscloset/octant:dev
    volumes:
      - "$HOME/kubeconfig:/kubeconfig:ro"
    networks:
      closet:
        ipv4_address: 192.168.0.3
    restart: always
  closetoctant_beta:
    image: devsecopscloset/octant:dev
    volumes:
      - "$HOME/kubeconfig:/kubeconfig:ro"
    networks:
      closet:
        ipv4_address: 192.168.0.4
    depends_on:
      - closetoctant_alpha
    restart: always

networks:
  closet:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/24
