version: '3'
services:
  loadbalancer:
    image: nginx
    ports: 
      - "443:443"
    volumes:
      - "$HOME/nginx:/etc/nginx:ro"
    depends_on:
      - closetdojo
      - closetoctant
  closetdojo_1:
    image: devsecopscloset/closet_dojo:dev
    networks:
      closet:
        ipv4_address: 192.168.0.2
    restart: always
  closetdojo_2:
    image: devsecopscloset/closet_dojo:dev
    networks:
      closet:
        ipv4_address: 192.168.0.3
    restart: always
  closetoctant_1:
    image: devsecopscloset/octant:dev
    volumes:
      - "$HOME/kubeconfig:/kubeconfig:ro"
    networks:
      closet:
        ipv4_address: 192.168.0.3
    restart: always
  closetoctant_2:
    image: devsecopscloset/octant:dev
    volumes:
      - "$HOME/kubeconfig:/kubeconfig:ro"
    networks:
      closet:
        ipv4_address: 192.168.0.4
    restart: always

networks:
  closet:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/24
