name: octant

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dev/images/octant/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dev/images/octant/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "devsecopscloset" --password-stdin
        docker image build /home/runner/work/components/components/dev/images/octant/ -t devsecopscloset/octant:dev 
        docker push devsecopscloset/octant:dev
